version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-apache
    steps:
      - checkout
      - run:
          name: Build dockerfile Docker Image
          command: |
            docker build -t dvwa .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run Trivy Scan
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
            trivy  dvwa
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

